import type { FlowupConfig } from '../config/types'
import type { WorkspacePackage } from '../monorepo'
import { existsSync } from 'node:fs'
import { cp, mkdir, rm, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import process from 'node:process'
import { scanMonorepoPackages } from '../monorepo'

export interface BundleOptions {
  /** monorepo 根,默认从 cwd 向上找 pnpm-workspace.yaml */
  rootDir?: string
  /** 显式指定要 bundle 的子包,默认扫全部 */
  packages?: string[]
  /** 顶层输出目录,相对 monorepo 根;默认 dist/commonNodes/node-red-tp-built-in */
  outputDir?: string
  /** 顶层 package.json 名,默认 'flowup-bundle' */
  name?: string
  /** 顶层 package.json version,默认 '1.0.0' */
  version?: string
  /** 顶层 package.json description */
  description?: string
  /** 顶层 package.json author */
  author?: string
  /** 顶层 package.json license,默认 'MIT' */
  license?: string
  /** bundle 完成后跑 pnpm install */
  install?: boolean
  /** 是否在已有产物上覆盖,默认 false */
  clean?: boolean
  /** bundle 阶段不跑 build,只整合现有 dist(便于手测或自定义 build 流程) */
  skipBuild?: boolean
  /** flowup 配置 */
  flowupConfig?: FlowupConfig | null
}

export interface BundleResult {
  rootDir: string
  outputDir: string
  /** 整合进 bundle 的子包清单 */
  packages: WorkspacePackage[]
  /** 顶层 package.json */
  manifest: Record<string, unknown>
}

const DEFAULT_OUTPUT = 'dist/commonNodes/node-red-tp-built-in'

export async function bundleMonorepo(rawOptions: BundleOptions = {}): Promise<BundleResult> {
  const opts: Required<Pick<BundleOptions, 'outputDir' | 'name' | 'version' | 'license' | 'install' | 'clean' | 'skipBuild'>> = {
    outputDir: rawOptions.outputDir
      ?? rawOptions.flowupConfig?.bundle?.output
      ?? DEFAULT_OUTPUT,
    name: rawOptions.name ?? rawOptions.flowupConfig?.bundle?.name ?? 'flowup-bundle',
    version: rawOptions.version ?? rawOptions.flowupConfig?.bundle?.version ?? '1.0.0',
    license: rawOptions.license ?? rawOptions.flowupConfig?.bundle?.license ?? 'MIT',
    install: rawOptions.install ?? rawOptions.flowupConfig?.bundle?.install ?? false,
    clean: rawOptions.clean ?? true,
    skipBuild: rawOptions.skipBuild ?? false,
  }

  // 1. 扫子包
  const scanOpts: { rootDir?: string, packages?: string[] } = {}
  if (rawOptions.rootDir)
    scanOpts.rootDir = rawOptions.rootDir
  if (rawOptions.packages)
    scanOpts.packages = rawOptions.packages
  else if (rawOptions.flowupConfig?.bundle?.packages)
    scanOpts.packages = rawOptions.flowupConfig.bundle.packages

  const { rootDir, packages } = await scanMonorepoPackages(
    rawOptions.rootDir ?? process.cwd(),
    scanOpts,
  )

  if (!packages.length) {
    throw new Error('No node-red packages found in workspace.')
  }

  const outputAbs = resolve(rootDir, opts.outputDir)
  if (opts.clean && existsSync(outputAbs)) {
    await rm(outputAbs, { recursive: true, force: true })
  }
  await mkdir(outputAbs, { recursive: true })

  // 2. 跑 build(每个子包)—— 默认跑,除非 skipBuild
  if (!opts.skipBuild) {
    const { buildEntry } = await import('../build/build')
    for (const pkg of packages) {
      const distDir = join(pkg.absPath, 'dist')
      if (!existsSync(distDir)) {
        // 该子包还没 build,先 build
        await buildEntry({
          cwd: pkg.absPath,
          flowupConfig: rawOptions.flowupConfig,
        })
      }
    }
  }

  // 3. 把每个子包的 dist 拷到 bundleDir/<scope>/
  for (const pkg of packages) {
    const distDir = join(pkg.absPath, 'dist')
    if (!existsSync(distDir)) {
      throw new Error(`Package ${pkg.name} has no dist directory at ${distDir}. Did you forget to build it?`)
    }
    const scope = (pkg.pkg['node-red'] as Record<string, unknown>)?.scope as string
      ?? pkg.relPath.split('/').pop()
      ?? pkg.name
    const targetDir = join(outputAbs, scope)
    await mkdir(targetDir, { recursive: true })
    await cp(distDir, targetDir, { recursive: true, force: true })
  }

  // 4. 写顶层 package.json
  const manifest = buildBundleManifest(packages, opts, rawOptions.flowupConfig)
  await writeFile(
    join(outputAbs, 'package.json'),
    `${JSON.stringify(manifest, null, 2)}\n`,
    'utf-8',
  )

  // 5. 写 README
  await writeFile(
    join(outputAbs, 'README.md'),
    `# ${opts.name}\n\nA Node-RED meta package that bundles ${packages.length} node(s) / plugin(s).\n\nGenerated by [flowup](https://github.com/wry-smile/flowup).\n`,
    'utf-8',
  )

  // 6. 写一份 .gitignore
  await writeFile(
    join(outputAbs, '.gitignore'),
    'node_modules\n',
    'utf-8',
  )

  // 7. 可选 pnpm install
  if (opts.install) {
    const { spawn } = await import('node:child_process')
    await new Promise<void>((resolve, reject) => {
      const child = spawn('pnpm', ['install'], { cwd: outputAbs, stdio: 'inherit' })
      child.on('exit', (code) => {
        if (code === 0)
          resolve()
        else
          reject(new Error(`pnpm install exited with code ${code}`))
      })
      child.on('error', reject)
    })
  }

  return {
    rootDir,
    outputDir: outputAbs,
    packages,
    manifest,
  }
}

function buildBundleManifest(
  packages: WorkspacePackage[],
  opts: Pick<Required<BundleOptions>, 'name' | 'version' | 'license'>,
  flowupConfig: FlowupConfig | null | undefined,
): Record<string, unknown> {
  const bundleCfg = flowupConfig?.bundle
  const description = bundleCfg?.description ?? `Node-RED meta package bundling ${packages.length} flowup-built component(s).`
  const author = bundleCfg?.author ?? ''

  const nodeRed: { nodes: Record<string, string>, plugins: Record<string, string> } = {
    nodes: {},
    plugins: {},
  }

  for (const pkg of packages) {
    const scope = (pkg.pkg['node-red'] as Record<string, unknown>)?.scope as string
      ?? pkg.relPath.split('/').pop()
      ?? pkg.name
    const nodeRedBlock = pkg.pkg['node-red'] as Record<string, unknown>
    if (nodeRedBlock?.nodes && typeof nodeRedBlock.nodes === 'object') {
      for (const [type, entry] of Object.entries(nodeRedBlock.nodes as Record<string, string>)) {
        const filename = entry.split('/').pop() ?? entry
        nodeRed.nodes[type] = `${scope}/${filename}`
      }
    }
    if (nodeRedBlock?.plugins && typeof nodeRedBlock.plugins === 'object') {
      for (const [type, entry] of Object.entries(nodeRedBlock.plugins as Record<string, string>)) {
        const filename = entry.split('/').pop() ?? entry
        nodeRed.plugins[type] = `${scope}/${filename}`
      }
    }
  }

  const manifest: Record<string, unknown> = {
    'name': opts.name,
    'version': opts.version,
    description,
    author,
    'license': opts.license,
    'type': 'module',
    'node-red': nodeRed,
  }
  return manifest
}

export { buildBundleManifest }
