shellEmulator: true

trustPolicy: no-downgrade

packages:
  - cli
  - packages/nodes/**
  - packages/plugins/**

catalog:
  '@antfu/eslint-config': ^9.0.0
  '@clack/prompts': ^0.11.0
  '@tailwindcss/vite': ^4.1.18
  '@types/js-yaml': ^4.0.9
  '@types/micromatch': ^4.0.10
  '@types/node': ^26.0.0
  '@types/node-red': ^1.3.5
  '@vitejs/plugin-vue': ^6.0.3
  '@wry-smile/utils': ^1.1.3
  bumpp: ^11.1.0
  commander: ^14.0.2
  eslint: ^10.5.0
  eslint-plugin-format: ^2.0.1
  find-up: ^5.0.0
  js-yaml: ^4.1.0
  micromatch: ^4.0.8
  node-red: ^5.0.0
  tsdown: ^0.20.1
  typescript: ^6.0.3
  vite: ^8.1.0
  vite-plugin-singlefile: ^2.3.0
